version: "2"
services:
  web:
    build: .
    depends_on:
      - db

    ports:
      - "8080:8080"
    volumes:
      - .:/vendor
      - /vendor/node_modules

  db:
    image: mongo
    expose:
      - "27017"
    volumes:
      - mongodata:/data/db
volumes:
  mongodata: